### ISSUE TITLE
Logging in Datei

### ISSUE THREAD

**Issue by marians** [marians/scrape-a-ris#12]
Ausgabe auf STDOUT/STDERR ist okay, wenn man auf der Konsole dem Scraper zusehen will. Wenn der Scraper über einen cronjob läuft, ist das nicht mehr so hilfreich.

Möglicherweise sollten verschiedene Loglevel (INFO/WARN/ERROR) unterstützt werden.

**Comment by the-infinity** [comment]
Da Python durch diesen Python 2.x Umlaute-Konstruktionsfehler nie wirklich mit dem Speichern von Logs via > umgehen können wird wäre dabei eine Log-Funktion innerhalb des Scrapers sinnvoll. Vielleicht mit Loglevel in der Config?

**Comment by marians** [comment]
Erledigt
